### PR TITLE
Merging fork into logstash-plugin repo

### PR DESCRIPTION
**Pull request by NickMRamirez**
Initial pull request for new plugin.

### CODE REVIEW

**Comment by purbon** [comment]
@jsvd @ph as windows heroes of logstash, can one of you take a look at this initial PR to have this plugin merge in?

**Comment by bradvido** [comment]
As another logstash & windows user, I'm going to be testing this out. Also looking forward to this being merged into an official plugin.

**Comment by purbon** [comment]
Cool,
   please go ahead, all testing is more than welcome, specially windows one.
you can use the issues of this repo to report issues.

We're going to merge this in as soon as is properly reviewed.

Looking forward to it,

On Friday, June 12, 2015, Brady Vidovic notifications@github.com wrote:

> As another logstash & windows user, I'm going to be testing this out. Also
> looking forward to this being merged into an official plugin.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logstash-plugins/logstash-input-perfmon/pull/1#issuecomment-111542818
> .

## 

Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by NickMRamirez** [comment]
It says that a CLA is missing for my last check-in. How do we fix that? And is testing still underway?

**Comment by purbon** [comment]
@NickMRamirez to get the CLA fix, you need to sign the CLA, or Contributor Agreement ... you can find more information at: https://www.elastic.co/contributor-agreement

Regarding testing, I'm not testing it right now, as of not being a windows expert myself ... i ask my colleagues in the group (@jsvd and @ph ) to provide his point of view. They are super busy, but I'm sure they will provide you with valuable feedback as soon as possible.

Thanks a lot for your patience and efforts.
- purbon

**Comment by NickMRamirez** [comment]
Can we at least get the initial pull request done? And then test as needed? Seems kinda silly to have an empty repo here.

**Comment by purbon** [comment]
@NickMRamirez you need to sign the CLA as requested: https://github.com/logstash-plugins/logstash-input-perfmon/pull/1#issuecomment-131754711 then we could move on more.

**Comment by NickMRamirez** [comment]
Is it not showing up? I no longer see the warning about the CLA.

**Comment by suyograo** [comment]
@NickMRamirez you have signed the cla using hotmail.com email. This PR is from email hmbnet.com domain. Can you please resign the cla with the hmbnet email?

**Comment by NickMRamirez** [comment]
I don't understand the CLA process then. My github account is tied to my gmail account. I'm not sure how either a hotmail or hmbnet email figures in. This is really just me not understanding. Did I specify those emails earlier?

**Comment by untergeek** [comment]
@NickMRamirez When signing the CLA, you had to manually provide an email address.  It did not come from your GitHub account automatically.

**Comment by NickMRamirez** [comment]
I forwarded it to my work email and signed it. Should be good now.

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by NickMRamirez** [comment]
Can I become a maintainer for this?

**Comment by karmi** [comment]
Hi @NickMRamirez, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-perfmon/pull/1.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
Hi @NickMRamirez, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-perfmon/pull/1.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by suyograo** [comment]
@NickMRamirez can you rebase? we can merge this in

**Comment by NickMRamirez** [comment]
I've added my other emails and signed the CLA again.

**Comment by NickMRamirez** [comment]
Where is this now? Need anything from me?

**Comment by NickMRamirez** [comment]
Checking in. Where do we stand with integrating this?

**Comment by talevy** [comment]
apologies @NickMRamirez, we have had some reorg on our team over the past few months. 

one thing that I see that would be great to do before we move forward is to update the gem dependencies so that this can be installed in Logstash >= 2.4.

```ruby
#gemspec file
s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60", "<= 2.99"
```

and maybe remove the explicit gem declarations in the `Gemfile`

thanks!

**Comment by NickMRamirez** [comment]
@talevy I would prefer it if this branch could be merged first. I've been waiting for that for quite a while. Then we can add your request as an Issue that either I or someone else can work on.

**Comment by talevy** [comment]
sure

**Pull request merged**
